version: '3'

services:
  dev-db:
    container_name: dev-db
    image: kartoza/postgis:12.0
    restart: always
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_EXTENSIONS: postgis
    volumes:
      # - ./postgres_data:/var/lib/postgresql/data
      - ./sql/setup-db.sql:/docker-entrypoint-initdb.d/setup-db.sql
    ports:
      - 5432:5432
